import test from 'node:test';
import assert from 'node:assert/strict';
import {SCHEMA,defaultView,validateRecipe,appendObservation,migrateClassic,LocalShelf,History} from '../web/workspace.mjs';
import {trailingBitRun,selectedRows,pairSeries} from '../web/panels.mjs';
const recipe=()=>({schema:SCHEMA,requests:{pair:{kind:'pair',seed:'27',relation:'flip',bit:3,map_left:'shortcut',map_right:'odd',steps:1000}},view:defaultView(),notes:'A <script> is only text',observations:[]});

test('versioned recipe has exact strings and copies its input',()=>{const r=recipe(),out=validateRecipe(r);out.requests.pair.seed='31';assert.equal(r.requests.pair.seed,'27');});
test('non-string exact seeds are rejected',()=>{const r=recipe();r.requests.pair.seed=9007199254740993;assert.throws(()=>validateRecipe(r));});
test('unknown schema and unknown operations reject',()=>{const r=recipe();r.schema='collatz-investigation/v9000';assert.throws(()=>validateRecipe(r));const q=recipe();q.requests.execute={kind:'execute',code:'bad'};assert.throws(()=>validateRecipe(q));});
test('missing selections remain explicit nulls',()=>{const r=recipe();r.view.left=null;assert.equal(validateRecipe(r).view.left,null);});
test('view bounds and filters are strict',()=>{for(const [key,value] of [['bitOffset',-1],['meetingIndex','constructor'],['meetingSupport','approximate'],['studyFilter','ignored'],['researchMetric',null],['left',Infinity],['bitWidth',9000]]){const r=recipe();r.view[key]=value;assert.throws(()=>validateRecipe(r));}});
test('observations round-trip as data, not code',()=>{const r=recipe();r.observations=[{title:'<img>',note:'<script>alert(1)</script>',status:'EMPIRICAL'}];assert.deepEqual(validateRecipe(r).observations,r.observations);});
test('named local shelf reads writes and deletes bounded recipes',()=>{const map=new Map(),shelf=new LocalShelf({getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)});shelf.save('Trial A',recipe());assert.equal(shelf.load('Trial A').requests.pair.seed,'27');shelf.remove('Trial A');assert.throws(()=>shelf.load('Trial A'));});
test('local shelf rejects prototype names and caps its count',()=>{const map=new Map(),shelf=new LocalShelf({getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)});assert.throws(()=>shelf.save('__proto__',recipe()));for(let i=0;i<12;i++)shelf.save('n'+i,recipe());assert.throws(()=>shelf.save('overflow',recipe()));});
test('history is bounded and redo is invalidated by a new computation',()=>{const h=new History(2);h.push('a');h.push('b');h.push('c');assert.equal(h.undo('d'),'c');assert.equal(h.redo('c'),'d');h.push('e');assert.equal(h.redo('f'),null);assert.equal(h.past.length,2);});
test('classic migration names its narrower scope and retains the old object',()=>{const r=migrateClassic({schema:'collatz-experiment/v1',orbit:{kind:'orbit',seed:'27',map:'odd',steps:2000},notes:'old',bookmarks:[],word:'1110'});assert.equal(r.requests.pair.delta,'2');assert.equal(r.importedClassic.word,'1110');assert.match(r.provenance.migration,/not claimed replayed/);});
test('sample trusted observable uses exact low bits',()=>{assert.deepEqual(trailingBitRun('8'),{bit:0,run:3});assert.deepEqual(trailingBitRun(String((1n<<1024n)-1n)),{bit:1,run:1024});assert.throws(()=>trailingBitRun('0'));});
test('raw plots include hidden intermediates, displayed plots preserve their maps',()=>{const row={n:'10',log2:3.3,raw:1,step:null};const state={data:{pair:{result:{left:{rows:[{n:'3',raw:0,i:0,log2:1.5}]},right:{rows:[{n:'10',raw:0,i:0,log2:3.3}]},raw_left:{rows:[{n:'3',raw:0,log2:1.5},row]},raw_right:{rows:[{n:'10',raw:0,log2:3.3}]},shared_raw:[]}}},view:{...defaultView(),left:1}};assert.equal(pairSeries(state)[0].length,2);assert.equal(selectedRows(state)[0].n,'10');state.view.alignment='displayed';assert.equal(pairSeries(state)[0].length,1);});
test('represented anchors remain inspectable past dense raw-prefix caps',()=>{const state={data:{pair:{result:{left:{rows:[{n:'7',raw:25000,i:9999}]},right:{rows:[]},raw_left:{rows:[]},raw_right:{rows:[]}}}},view:{left:25000,right:0}};assert.deepEqual(selectedRows(state)[0],{n:'7',raw:25000,i:9999,step:9999});assert.equal(selectedRows(state)[1],null);});

test('an observation that exceeds portable size is rejected without changing prior evidence',()=>{const r=recipe();r.observations=Array.from({length:99},()=>({title:'A',note:'x'.repeat(20000)}));validateRecipe(r);assert.throws(()=>appendObservation(r,{title:'B',note:'y'.repeat(20000)}));assert.equal(r.observations.length,99);});
